= Running with Docker Compose
:icons: font
:toc:
:toc-title:
:toc-placement: manual
:toclevels: 2
:sociallogin: link:adding_your_own_sso_apps_for_local_testing.adoc
:wdt-eclipse: link:eclipse_and_wdt.adoc
:12-factor: link:../about/twelve-factors.adoc
:docker: https://docs.docker.com/engine/installation/
:git: link:git.adoc
:vagrant: https://www.vagrantup.com/downloads.html
:root: https://github.com/gameontext/gameon
:adventures: link:createMore.adoc
:contribute: https://github.com/gameontext/gameon/blob/master/CONTRIBUTING.md
:compose: https://docs.docker.com/compose/install/
:releases: https://github.com/docker/compose/releases

== Requirements

Game On! requires `docker-compose` {releases}[version 1.15.0 or greater].
{compose}[Installation instructions] vary by platform. 

[[running]]
== Starting game services locally 

1. Obtain the source for the root project ({root}[gameontext/gameon]) 
  * HTTPS: `git clone https://github.com/gameontext/gameon.git`
  * SSH: `git clone git@github.com:gameontext/gameon.git`

2. Change to the gameon directory
+
-------------------------------------------
cd gameon
-------------------------------------------
3. Setup your environment (one time). 
+
-------------------------------------------
./docker/go-setup.sh
-------------------------------------------
+
This will ensure that you have an env file suitable for use 
with `docker-compose` and pulls the initial images required 
for running the system. 
+
When using Vagrant, this step is done as part of provisioning the VM.

4. Start the game!
+
-------------------------------------------
./docker/go-run.sh up
-------------------------------------------
5. Wait for the system warm up
+
-------------------------------------------
./docker/go-run.sh wait
-------------------------------------------
or, to watch the logs stream by, try:
+
-------------------------------------------
./docker/go-run.sh logs
-------------------------------------------

6. (Optional) Set the COMPOSE environment variable so you can work with `docker-compose` 
directly (see <<go-run,below>>).

7. *Carry on with {adventures}[building your room]!*

8. Clean up 
+
-------------------------------------------
./docker/go-run.sh down
-------------------------------------------

== Files supporting Docker Compose

The `docker` subdirectory of the root project
contains the files required to make game services go: 

* `docker-compose.yml` declares core game and required backing services
* `docker-compose.override.yml.example` can be copied to `docker-compose.override.yml` 
  and modified to support overlays for local development
* `go-setup.sh` is a script to help configure your local environment to work 
  with Docker Compose 
* `go-run.sh` helps with starting, stopping, and cleaning up Game ON core services.
* `docker-functions` is used by both `go-setup.sh` and `go-run.sh` to 
  generate the keystore volume and generate the `COMPOSE` environment variable.

[[go-run]]
[NOTE]
.About `go-run.sh` and `COMPOSE`
====
- Use `./docker/go-run.sh` to get a list of available actions. Some examples:
+
-------------------------------------------
./docker/go-run.sh up
./docker/go-run.sh down
./docker/go-run.sh logs
./docker/go-run.sh rebuild
./docker/go-run.sh restart
./docker/go-run.sh wait
-------------------------------------------
- Use `eval $(./docker/go-run.sh env)` to add the `COMPOSE` environment variable
  to your shell to help run `docker-compose` commands directly. For example:
+
-------------------------------------------
eval $(./docker/go-run.sh env)
echo ${COMPOSE}
${COMPOSE} ps
${COMPOSE} logs
-------------------------------------------
The `COMPOSE` environment variable includes `-f` options for `docker-compose.yml` and 
`docker-compose.override.yml` (if present), and `sudo` (if required).
====

Additional notes for running with Docker Compose: 

* `docker-compose` still requires sudo on linux platforms, even
though `docker` doesn't.
* The Vagrant VM allows all `sudo` operations with no password.

[[rebuild]]
== Rebuilding Core Game services with Docker Compose

The following instructions assume you've cloned the root repository, 
and are interested in editing the `map` service as an example: 

1. Change to the gameon directory
+
-------------------------------------------
cd gameon
-------------------------------------------
2. Obtain the source for the project that you want to change.
+
-------------------------------------------
git submodule init map
git submodule update map
-------------------------------------------
3. Make your changes from within the child directory
+
-------------------------------------------
cd map
git checkout -b newbranch
-------------------------------------------
Edit source or docker/image files using your favorite IDE.
+
TIP: If you plan to edit projects with Eclipse, run `./bin/eclipse.sh` to generate eclipse project files.

4. Compile the source and rebuild docker image
* To rebuild and restart the map service:  
+
-------------------------------------------
./docker/go-run.sh rebuild map
-------------------------------------------
* To rebuild the image without recreating the container:  
+
-------------------------------------------
./docker/go-run.sh rebuild_only map
-------------------------------------------
* If the service argument is left off, it will attempt to rebuild all
of the core services (auth, map, mediator, player, room, webapp). If those 
submodules haven't been checked out, there is no harm. The image from dockerhub
will be used instead.
+
[NOTE]
.Top-down vs. incremental updates
====
If you want to try using incremental publish, where your changes are live inside
the container without requiring the container to be stopped, started, rebuilt
or otherwise messed with, you'll need to create and/or add some lines 
to `./docker/docker-compose.override.yml` to create overlay volumes.

`./docker/docker-compose.override.yml.example` provides examples of how
to map expected github subrepository paths to volumes. Copy snippets from 
that file for the services you're interested in into `docker-compose.override.yml`.

`./docker/go-run.sh` will accommodate the creation of the `docker-compose.override.yml`
file, but you may need to run `eval $(./docker/go-run.sh env)` to update your
`COMPOSE` environment variable.
====

5. Push your changes to a new branch. From the map directory: 
+
-------------------------------------------
git add -u
git commit -s  
-------------------------------------------
+
[NOTE]
====
Git commits must be {contribute}[signed]
====
Once you make your commit, if you go back to the root directory, you will see 
a pending change for map. This indicates that the submodule is different than
the version from the current branch of the root project. *Do not
check in this change.* Sadly, these files can not be added to `.gitignore`.
+
Care must be taken to avoid staging these files if you otherwise end up making
changes to files in the root project itself.

 

